In [1]:
import numpy as np 
import pandas as pd 
import os 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6


In [3]:
df =pd.read_csv("C:\\Users\\Srinu Jaddu\\OneDrive\\Desktop\\DATASETS\\prices.csv", header=0)
display (df)

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
...                     ...    ...         ...         ...         ...   
851259           2016-12-30    ZBH  103.309998  103.199997  102.849998   
851260           2016-12-30   ZION   43.070000   43.040001   42.689999   
851261           2016-12-30    ZTS   53.639999   53.529999   53.270000   
851262  2016-12-30 00:00:00    AIV   44.730000   45.450001   44.410000   
851263  2016-12-30 00:00:00    FTV   54.200001   53.630001   53.389999   

              high     volume  
0       126.250000  2163600.0  
1       125.540001  2386400.0  
2       119.739998  2489500.0  
3       117.440002  2006300.0  
4       117.330002  1408600.0  
...            ...        ...  
851259  103.930000   973800.0  
851260   43.310001  1938100.0  
851261   53.740002  1701200.0  
851262   45.590000  1380900.0  
851263   54.480000   705100.0  

[851264 rows x 7 columns]

In [4]:
print(df.shape)

(851264, 7)


In [5]:
print(df.columns)


Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')


In [6]:
df.symbol.value_counts()

KSU     1762
NOC     1762
ORCL    1762
OMC     1762
OKE     1762
        ... 
KHC      378
HPE      304
CSRA     284
WLTW     251
FTV      126
Name: symbol, Length: 501, dtype: int64

In [7]:
df.symbol.unique()

array(['WLTW', 'A', 'AAL', 'AAP', 'AAPL', 'ABC', 'ABT', 'ACN', 'ADBE',
       'ADI', 'ADM', 'ADP', 'ADS', 'ADSK', 'AEE', 'AEP', 'AES', 'AET',
       'AFL', 'AGN', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALK', 'ALL',
       'ALXN', 'AMAT', 'AME', 'AMG', 'AMGN', 'AMP', 'AMT', 'AMZN', 'AN',
       'ANTM', 'AON', 'APA', 'APC', 'APD', 'APH', 'ARNC', 'ATVI', 'AVB',
       'AVGO', 'AVY', 'AWK', 'AXP', 'AYI', 'AZO', 'BA', 'BAC', 'BAX',
       'BBBY', 'BBT', 'BBY', 'BCR', 'BDX', 'BEN', 'BHI', 'BIIB', 'BK',
       'BLK', 'BLL', 'BMY', 'BSX', 'BWA', 'BXP', 'C', 'CA', 'CAG', 'CAH',
       'CAT', 'CB', 'CBG', 'CBS', 'CCI', 'CCL', 'CELG', 'CERN', 'CF',
       'CHD', 'CHK', 'CHRW', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA',
       'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COG', 'COH',
       'COL', 'COO', 'COP', 'COST', 'CPB', 'CRM', 'CSCO', 'CSX', 'CTAS',
       'CTL', 'CTSH', 'CTXS', 'CVS', 'CVX', 'CXO', 'D', 'DAL', 'DD', 'DE',
       'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DISCA', 'DISCK', 

In [8]:
display(df.symbol.unique().shape)

(501,)

In [9]:
df.symbol.unique()[0:20]


array(['WLTW', 'A', 'AAL', 'AAP', 'AAPL', 'ABC', 'ABT', 'ACN', 'ADBE',
       'ADI', 'ADM', 'ADP', 'ADS', 'ADSK', 'AEE', 'AEP', 'AES', 'AET',
       'AFL', 'AGN'], dtype=object)

In [10]:
print(len(df.symbol.values))

851264


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    851264 non-null  object 
 1   symbol  851264 non-null  object 
 2   open    851264 non-null  float64
 3   close   851264 non-null  float64
 4   low     851264 non-null  float64
 5   high    851264 non-null  float64
 6   volume  851264 non-null  float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [12]:
df.describe()

open          close            low           high  \
count  851264.000000  851264.000000  851264.000000  851264.000000   
mean       70.836986      70.857109      70.118414      71.543476   
std        83.695876      83.689686      82.877294      84.465504   
min         0.850000       0.860000       0.830000       0.880000   
25%        33.840000      33.849998      33.480000      34.189999   
50%        52.770000      52.799999      52.230000      53.310001   
75%        79.879997      79.889999      79.110001      80.610001   
max      1584.439941    1578.130005    1549.939941    1600.930054   

             volume  
count  8.512640e+05  
mean   5.415113e+06  
std    1.249468e+07  
min    0.000000e+00  
25%    1.221500e+06  
50%    2.476250e+06  
75%    5.222500e+06  
max    8.596434e+08

In [13]:
df.date.unique()

array(['2016-01-05 00:00:00', '2016-01-06 00:00:00',
       '2016-01-07 00:00:00', ..., '2016-12-28', '2016-12-29',
       '2016-12-30'], dtype=object)

In [14]:
pd.DataFrame(df.date.unique())

0
0     2016-01-05 00:00:00
1     2016-01-06 00:00:00
2     2016-01-07 00:00:00
3     2016-01-08 00:00:00
4     2016-01-11 00:00:00
...                   ...
3519           2016-12-23
3520           2016-12-27
3521           2016-12-28
3522           2016-12-29
3523           2016-12-30

[3524 rows x 1 columns]

In [15]:
df.duplicated().sum()


0

In [18]:
comp_info = pd.read_csv("C:\\Users\\Srinu Jaddu\\OneDrive\\Desktop\\DATASETS\\securities.csv")
comp_info


Ticker symbol                Security SEC filings             GICS Sector  \
0             MMM              3M Company     reports             Industrials   
1             ABT     Abbott Laboratories     reports             Health Care   
2            ABBV                  AbbVie     reports             Health Care   
3             ACN           Accenture plc     reports  Information Technology   
4            ATVI     Activision Blizzard     reports  Information Technology   
..            ...                     ...         ...                     ...   
500          YHOO              Yahoo Inc.     reports  Information Technology   
501           YUM         Yum! Brands Inc     reports  Consumer Discretionary   
502           ZBH  Zimmer Biomet Holdings     reports             Health Care   
503          ZION           Zions Bancorp     reports              Financials   
504           ZTS                  Zoetis     reports             Health Care   

                  GICS Sub Industry   Address of Headquarters  \
0          Industrial Conglomerates       St. Paul, Minnesota   
1             Health Care Equipment   North Chicago, Illinois   
2                   Pharmaceuticals   North Chicago, Illinois   
3    IT Consulting & Other Services           Dublin, Ireland   
4       Home Entertainment Software  Santa Monica, California   
..                              ...                       ...   
500    Internet Software & Services     Sunnyvale, California   
501                     Restaurants      Louisville, Kentucky   
502           Health Care Equipment           Warsaw, Indiana   
503                  Regional Banks      Salt Lake City, Utah   
504                 Pharmaceuticals  Florham Park, New Jersey   

    Date first added      CIK  
0                NaN    66740  
1         31-03-1964     1800  
2         31-12-2012  1551152  
3         06-07-2011  1467373  
4         31-08-2015   718877  
..               ...      ...  
500              NaN  1011006  
501       06-10-1997  1041061  
502              NaN  1136869  
503              NaN   109380  
504       21-06-2013  1555280  

[505 rows x 8 columns]

In [19]:
comp_info["Ticker symbol"].nunique()

505

In [20]:
comp_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Ticker symbol            505 non-null    object
 1   Security                 505 non-null    object
 2   SEC filings              505 non-null    object
 3   GICS Sector              505 non-null    object
 4   GICS Sub Industry        505 non-null    object
 5   Address of Headquarters  505 non-null    object
 6   Date first added         307 non-null    object
 7   CIK                      505 non-null    int64 
dtypes: int64(1), object(7)
memory usage: 31.7+ KB


In [21]:
comp_info.isnull().sum()

Ticker symbol                0
Security                     0
SEC filings                  0
GICS Sector                  0
GICS Sub Industry            0
Address of Headquarters      0
Date first added           198
CIK                          0
dtype: int64

In [22]:
comp_info.describe()

CIK
count  5.050000e+02
mean   7.074490e+05
std    5.144375e+05
min    1.800000e+03
25%    8.631200e+04
50%    8.310010e+05
75%    1.075531e+06
max    1.659166e+06

In [23]:
comp_info.loc[comp_info.Security.str.startswith('Face') , :]

Ticker symbol  Security SEC filings             GICS Sector  \
181            FB  Facebook     reports  Information Technology   

                GICS Sub Industry Address of Headquarters Date first added  \
181  Internet Software & Services  Menlo Park, California       23-12-2013   

         CIK  
181  1326801

In [24]:
comp_info.loc[comp_info.Security.str.startswith('Acc') , :]

Ticker symbol       Security SEC filings             GICS Sector  \
3           ACN  Accenture plc     reports  Information Technology   

                GICS Sub Industry Address of Headquarters Date first added  \
3  IT Consulting & Other Services         Dublin, Ireland       06-07-2011   

       CIK  
3  1467373

In [25]:
comp_plot = comp_info.loc[(comp_info["Security"] == 'Yahoo Inc.') | (comp_info["Security"] == 'Xerox Corp.') | (comp_info["Security"] == 'Adobe Systems Inc')
              | (comp_info["Security"] == 'Microsoft Corp.') | (comp_info["Security"] == 'Adobe Systems Inc') 
              | (comp_info["Security"] == 'Facebook') | (comp_info["Security"] == 'Goldman Sachs Group') , ["Ticker symbol"] ]["Ticker symbol"] 
print(comp_plot)


6      ADBE
181      FB
212      GS
306    MSFT
496     XRX
500    YHOO
Name: Ticker symbol, dtype: object


In [26]:
for i in comp_plot:
    print (i)


ADBE
FB
GS
MSFT
XRX
YHOO


In [30]:
def plotter(code):
    # Function used to create graphs for 6 companies 
    global closing_stock ,opening_stock
    #creating plot of all 6 company for opening and closing stock  total 12 graphs
    # Below statement create 2X2 empty chart 
    f, axs = plt.subplots(2,2,figsize=(15,8))
    # total 12 graphs
    # creating plot opening prize of particular company
    plt.subplot(212)
    #taking name of the company as code, get all records related to one company
    company = df[df['symbol']==code]
    #taking the values of one company and taking its open column values to 1D array
    company = company.open.values.astype('float32')
    #reshaping the open stock value from 1D  to 2D .
    company = company.reshape(-1, 1)
    # putting the value of company in opening_stock 
    opening_stock = company
    plt.grid(True)# enalbling the grid in graph
    plt.xlabel('Time') # setting X axis as time
    # setting Y axis as company name + open stock prices
    plt.ylabel(code + " open stock prices") 
    plt.title('prices Vs Time') # setting title
    plt.plot(company , 'g') # calling the graph with green graph line
    
    # creating plot closing prize of particular company
    plt.subplot(211)
    #taking name of the company as code
    company_close = df[df['symbol']==code]
    #taking the values of one company and taking its close column values
    company_close = company_close.close.values.astype('float32')
    #reshaping the open column value in 1D and calling it closing_stock
   # -1 for unknown dimension
    company_close = company_close.reshape(-1, 1)
    # putting company_close value in closing_stock 
    closing_stock = company_close
    # plotting the data graph between "Time" and "prices vs time"
    plt.xlabel('Time') # setting x axis as time
    plt.ylabel(code + " close stock prices")# setting y axis as company name + open stock prices
    plt.title('prices Vs Time') # setting title as price vs time
    plt.grid(True) # enabling the grid in graph
    plt.plot(company_close , 'b') #creating the data graph in blue graph line
    plt.show() # calling the graph
    for i in comp_plot:
        plotter(i)





In [31]:
stocks= np.array (df[df.symbol.isin (['YHOO'])].close)
print(stocks)


[17.1      17.23     17.17     ... 38.73     38.639999 38.669998]


In [32]:

display (stocks.shape)


(1762,)

In [33]:
stocks = stocks.reshape(len(stocks) , 1)
print (stocks.shape)
print(stocks)


(1762, 1)
[[17.1     ]
 [17.23    ]
 [17.17    ]
 ...
 [38.73    ]
 [38.639999]
 [38.669998]]


In [34]:
from sklearn.preprocessing import MinMaxScaler
#scaling features between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1)) 
stocks = scaler.fit_transform(stocks) 
display (stocks)


array([[0.14559109],
       [0.14874031],
       [0.14728683],
       ...,
       [0.66957366],
       [0.6673934 ],
       [0.66812012]])

In [35]:
print (stocks.shape) 

# 80 % Training record count   
train = int(len(stocks) * 0.80)
print (train)

# 20 % record count    (Total – 80%)
test = len(stocks) - train 
print (test)


(1762, 1)
1409
353


In [38]:
# Training Data
#divinding the values of stocks data to train from 0 to 1409 i.e 80% data
train = stocks[0:train]
display (train.shape)
print(train)

# Test Data
#divinding the values of stocks data to test from train ending to stock data ending i.e rest 20% data
test = stocks[len(train) : ]
display(test.shape)
display (test)



(1409, 1)

[[0.14559109]
 [0.14874031]
 [0.14728683]
 ...
 [0.63372095]
 [0.61458332]
 [0.61967051]]


(353, 1)

array([[0.63129851],
       [0.60416666],
       [0.56686053],
       [0.6017442 ],
       [0.60925394],
       [0.60586237],
       [0.59593022],
       [0.58381782],
       [0.55741276],
       [0.52906978],
       [0.48982557],
       [0.50024226],
       [0.51913761],
       [0.54748061],
       [0.53415697],
       [0.51235471],
       [0.49685079],
       [0.500969  ],
       [0.51962213],
       [0.49636629],
       [0.47989342],
       [0.4949128 ],
       [0.48594962],
       [0.49273257],
       [0.46584303],
       [0.48328492],
       [0.49200583],
       [0.48062017],
       [0.47601745],
       [0.48643412],
       [0.46778102],
       [0.45179265],
       [0.44210272],
       [0.43701549],
       [0.39995156],
       [0.41593993],
       [0.43168606],
       [0.43168606],
       [0.47529068],
       [0.47868218],
       [0.48134689],
       [0.50339151],
       [0.51550386],
       [0.51913761],
       [0.52737407],
       [0.51477714],
       [0.50872094],
       [0.542

In [39]:
def process_data(data , n_features):
    dataX, dataY = [], [] # creating data for dataset and dividing inta X,Y
    for i in range(len(data)-n_features):
        # taking i range from total size- 3 
        a = data[i:(i+n_features), 0]
        # Here a is value of data from i to i+ n_features, ie two values and put it in dataX 
        dataX.append(a) #putting a in dataX
        #here dataY takes the value of data of i + n_features
        dataY.append(data[i + n_features, 0])
        # putting i+ n_features in  dataY
    return np.array(dataX), np.array(dataY)
# returning dataX and dataY in array



In [41]:
n_features = 2
trainX, trainY = process_data(train, n_features)
print(trainX.shape , trainY.shape)



(1407, 2) (1407,)


In [42]:
testX, testY = process_data(test, n_features)
print (testX.shape , testY.shape)


(351, 2) (351,)


In [43]:
stocksX, stocksY = process_data(stocks, n_features)
print (stocksX.shape , stocksY.shape)


(1760, 2) (1760,)


In [45]:
display (trainX[:10])

array([[0.14559109, 0.14874031],
       [0.14874031, 0.14728683],
       [0.14728683, 0.13590119],
       [0.13590119, 0.13590119],
       [0.13590119, 0.13687016],
       [0.13687016, 0.13541667],
       [0.13541667, 0.14074613],
       [0.14074613, 0.14607561],
       [0.14607561, 0.13880814],
       [0.13880814, 0.13711241]])

In [46]:
display (trainY[:10])

array([0.14728683, 0.13590119, 0.13590119, 0.13687016, 0.13541667,
       0.14074613, 0.14607561, 0.13880814, 0.13711241, 0.1281492 ])

In [47]:
trainX = trainX.reshape(trainX.shape[0] , 1 ,trainX.shape[1])
display (trainX.shape)

(1407, 1, 2)

In [48]:
testX = testX.reshape(testX.shape[0] , 1 ,testX.shape[1])
display (testX.shape)


(351, 1, 2)

In [49]:
stocksX= stocksX.reshape(stocksX.shape[0] , 1 ,stocksX.shape[1])
display (stocksX.shape)



(1760, 1, 2)